-- MySQL Script generated by MySQL Workbench
-- Sat Feb 29 18:14:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ar` ;

-- -----------------------------------------------------
-- Schema ar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ar` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema cfg
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cfg` ;

-- -----------------------------------------------------
-- Schema cfg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cfg` ;
USE `ar` ;

-- -----------------------------------------------------
-- Table `ar`.`Accident`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`Accident` ;

CREATE TABLE IF NOT EXISTS `ar`.`Accident` (
  `AccidentID` INT NOT NULL AUTO_INCREMENT,
  `DateOfAccident` VARCHAR(255) NULL,
  `TimeOfAccident` VARCHAR(255) NULL,
  `AddressLocation` VARCHAR(255) NULL,
  `Logitude` VARCHAR(255) NULL,
  `Latitude` VARCHAR(255) NULL,
  `City` VARCHAR(255) NULL,
  `Region` VARCHAR(255) NULL,
  `WeatherDuringAccident` VARCHAR(255) NULL,
  `RoadType` VARCHAR(255) NULL,
  `RoadClassification` VARCHAR(255) NULL,
  `RoadCondition` VARCHAR(255) NULL,
  `ReportingOfficerName` VARCHAR(255) NULL,
  `ReportingOfficerStataion` VARCHAR(255) NULL,
  `ReportingOfficerPhone` VARCHAR(255) NULL,
  `NumberOfVehiclesInvolved` INT NULL,
  `NumberOfPeopleInvolved` INT NULL,
  `NumberOfDeath` INT NULL,
  `NUmberOfMajorInjury` INT NULL,
  `NumberOfModerateInjury` INT NULL,
  `NUmberOfMinorInjury` INT NULL,
  `UknownInjury` INT NULL,
  `AccidentType` VARCHAR(255) NULL,
  `LegalRoadSpeed_KMh` VARCHAR(45) NULL,
  `DateCreated` DATETIME NULL,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` DATETIME NULL,
  `AdditionalInfo` VARCHAR(255) NULL,
  PRIMARY KEY (`AccidentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`Attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`Attachment` ;

CREATE TABLE IF NOT EXISTS `ar`.`Attachment` (
  `AttachmentID` INT NOT NULL AUTO_INCREMENT,
  `AccidentID` INT NULL,
  `AttachmentType` VARCHAR(255) NULL,
  `Attachment` VARBINARY(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  PRIMARY KEY (`AttachmentID`),
  INDEX `FK_AccidentID_Attachment_idx` (`AccidentID` ASC) VISIBLE,
  CONSTRAINT `FK_AccidentID_Attachment`
    FOREIGN KEY (`AccidentID`)
    REFERENCES `ar`.`Accident` (`AccidentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`Employee` ;

CREATE TABLE IF NOT EXISTS `ar`.`Employee` (
  `EmployeeId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NULL,
  `LastName` VARCHAR(255) NULL,
  `UserName` VARCHAR(255) NULL,
  `Password` VARCHAR(255) NULL,
  `PasswordSalt` VARCHAR(255) NULL,
  `PasswordHash` VARCHAR(255) NULL,
  `IsActive` BIT NULL DEFAULT 1,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  `UpdatedBy` VARCHAR(255) NULL,
  `AccessLockoutEnd` DATETIME NULL,
  `LoginFailedCount` SMALLINT NULL DEFAULT 0,
  `LastAccessedDate` DATETIME NULL,
  `AdditionalInfo` VARCHAR(1024) NULL,
  `LoginLockoutEnabled` BIT NULL DEFAULT 0,
  PRIMARY KEY (`EmployeeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`EmployeeContact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`EmployeeContact` ;

CREATE TABLE IF NOT EXISTS `ar`.`EmployeeContact` (
  `EmployeeContactID` INT NOT NULL AUTO_INCREMENT,
  `EmployeeId` INT NULL,
  `Department` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `EmailConfirmed` BIT NULL DEFAULT 0,
  `TowFactorEnabled` BIT NULL DEFAULT 0,
  `AddressLocation` VARCHAR(1024) NULL,
  `City` VARCHAR(255) NULL,
  `Region` VARCHAR(255) NULL,
  `PhoneNumberMobile` VARCHAR(255) NULL,
  `PhoneNumberOffice` VARCHAR(255) NULL,
  `PhoneNumber2` VARCHAR(255) NULL,
  `PhoneNumber2Type` VARCHAR(255) NULL,
  `PhoneNumber3` VARCHAR(255) NULL,
  `PhoneNumber3Type` VARCHAR(45) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  `UpdatedBy` VARCHAR(255) NULL,
  PRIMARY KEY (`EmployeeContactID`),
  INDEX `FK_EmployeeID_EmployeeContact_idx` (`EmployeeId` ASC) VISIBLE,
  CONSTRAINT `FK_EmployeeID_EmployeeContact`
    FOREIGN KEY (`EmployeeId`)
    REFERENCES `ar`.`Employee` (`EmployeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`Role` ;

CREATE TABLE IF NOT EXISTS `ar`.`Role` (
  `RoleId` INT NOT NULL,
  `RoleName` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  `UpdatedBy` VARCHAR(255) NULL,
  PRIMARY KEY (`RoleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`EmployeeRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`EmployeeRole` ;

CREATE TABLE IF NOT EXISTS `ar`.`EmployeeRole` (
  `EmployeeRoleId` INT NOT NULL AUTO_INCREMENT,
  `EmployeeId` INT NULL,
  `RoleId` INT NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  `UpdatedBy` VARCHAR(255) NULL,
  PRIMARY KEY (`EmployeeRoleId`),
  INDEX `FK_EmployeeId_EmployeeRole_idx` (`EmployeeId` ASC) VISIBLE,
  INDEX `FK_RoleId_EmployeeRole_idx` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_EmployeeId_EmployeeRole`
    FOREIGN KEY (`EmployeeId`)
    REFERENCES `ar`.`Employee` (`EmployeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RoleId_EmployeeRole`
    FOREIGN KEY (`RoleId`)
    REFERENCES `ar`.`Role` (`RoleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`Vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`Vehicle` ;

CREATE TABLE IF NOT EXISTS `ar`.`Vehicle` (
  `VehicleID` INT NOT NULL AUTO_INCREMENT,
  `AccidentID` INT NULL,
  `Make` VARCHAR(255) NULL,
  `Model` VARCHAR(255) NULL,
  `Year` INT NULL,
  `Color` VARCHAR(255) NULL,
  `VehicleType` VARCHAR(255) NULL,
  `PlateNumber` VARCHAR(255) NULL,
  `VIN` VARCHAR(255) NULL,
  `HasInsurance` BIT NULL,
  `DamageClass` VARCHAR(255) NULL,
  `AccidentPosition` VARCHAR(255) NULL,
  `VehicleSpeedBeforeAccident_KMh` INT NULL,
  `MannerOfCollision` VARCHAR(255) NULL,
  `VehicleOwner` VARCHAR(255) NULL,
  `AdditionalInfo` VARCHAR(1024) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  PRIMARY KEY (`VehicleID`),
  INDEX `FK_AccidentID_Vehicle_idx` (`AccidentID` ASC) VISIBLE,
  CONSTRAINT `FK_AccidentID_Vehicle`
    FOREIGN KEY (`AccidentID`)
    REFERENCES `ar`.`Accident` (`AccidentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`Motorist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`Motorist` ;

CREATE TABLE IF NOT EXISTS `ar`.`Motorist` (
  `MotoristID` INT NOT NULL AUTO_INCREMENT,
  `VehicleID` INT NULL,
  `LicenseNumber` VARCHAR(255) NULL,
  `IssuedState` VARCHAR(255) NULL,
  `IssuedCountry` VARCHAR(255) NULL,
  `IssuedDate` DATETIME NULL,
  `MotorisReadiness` VARCHAR(255) NULL,
  `Education` VARCHAR(255) NULL,
  `HasLicense` BIT NULL,
  `AdditionalInfo` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  PRIMARY KEY (`MotoristID`),
  INDEX `FK_VehicleID_Motorist_idx` (`VehicleID` ASC) VISIBLE,
  CONSTRAINT `FK_VehicleID_Motorist`
    FOREIGN KEY (`VehicleID`)
    REFERENCES `ar`.`Vehicle` (`VehicleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`OldPassword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`OldPassword` ;

CREATE TABLE IF NOT EXISTS `ar`.`OldPassword` (
  `OldPasswordId` INT NOT NULL AUTO_INCREMENT,
  `EmployeeId` INT NULL,
  `OldPassword` VARCHAR(255) NULL,
  `OldPasswordHash` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  `UpdatedBy` VARCHAR(255) NULL,
  PRIMARY KEY (`OldPasswordId`),
  INDEX `FK_EmployeeID_OldPassword_idx` (`EmployeeId` ASC) VISIBLE,
  CONSTRAINT `FK_EmployeeID_OldPassword`
    FOREIGN KEY (`EmployeeId`)
    REFERENCES `ar`.`Employee` (`EmployeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`Pedastrian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`Pedastrian` ;

CREATE TABLE IF NOT EXISTS `ar`.`Pedastrian` (
  `PedastrianID` INT NOT NULL AUTO_INCREMENT,
  `VehicleID` INT NULL,
  `FirstName` VARCHAR(255) NULL,
  `MIddleName` VARCHAR(255) NULL,
  `LastName` VARCHAR(255) NULL,
  `Age` INT NULL,
  `Sex` VARCHAR(255) NULL,
  `Address` VARCHAR(1024) NULL,
  `PhoneNumber` VARCHAR(255) NULL,
  `InjuryClass` VARCHAR(255) NULL,
  `PositionDuringAccident` VARCHAR(255) NULL,
  `AdditionalInfo` VARCHAR(1024) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PedastrianID`),
  INDEX `FK_VehicleID_Pedastrian_idx` (`VehicleID` ASC) VISIBLE,
  CONSTRAINT `FK_VehicleID_Pedastrian`
    FOREIGN KEY (`VehicleID`)
    REFERENCES `ar`.`Vehicle` (`VehicleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`PersonInVehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`PersonInVehicle` ;

CREATE TABLE IF NOT EXISTS `ar`.`PersonInVehicle` (
  `PersonID` INT NOT NULL AUTO_INCREMENT,
  `VehicleID` INT NULL,
  `FirstName` VARCHAR(255) NULL,
  `MIddleName` VARCHAR(255) NULL,
  `LastName` VARCHAR(255) NULL,
  `Age` INT NULL,
  `Sex` VARCHAR(255) NULL,
  `Address` VARCHAR(1024) NULL,
  `PhoneNumber` VARCHAR(255) NULL,
  `PersonType` VARCHAR(255) NULL,
  `InjuryClass` VARCHAR(255) NULL,
  `RestraintUsed` VARCHAR(255) NULL,
  `AdditionalInfo` VARCHAR(1024) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  PRIMARY KEY (`PersonID`),
  INDEX `FK_VehicleID_Person_idx` (`VehicleID` ASC) VISIBLE,
  CONSTRAINT `FK_VehicleID_Person`
    FOREIGN KEY (`VehicleID`)
    REFERENCES `ar`.`Vehicle` (`VehicleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ar`.`RoadType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ar`.`RoadType` ;

CREATE TABLE IF NOT EXISTS `ar`.`RoadType` (
  `RoadTypeId` INT NOT NULL AUTO_INCREMENT,
  `RoadType` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL,
  `UpdatedBy` VARCHAR(45) NULL,
  PRIMARY KEY (`RoadTypeId`))
ENGINE = InnoDB;

USE `cfg` ;

-- -----------------------------------------------------
-- Table `cfg`.`AccidentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`AccidentType` ;

CREATE TABLE IF NOT EXISTS `cfg`.`AccidentType` (
  `AccidentTypeID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AccidentTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfg`.`InjuryClass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`InjuryClass` ;

CREATE TABLE IF NOT EXISTS `cfg`.`InjuryClass` (
  `InjuryClassID` INT NOT NULL AUTO_INCREMENT,
  `Class` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`InjuryClassID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfg`.`MannerOfCollision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`MannerOfCollision` ;

CREATE TABLE IF NOT EXISTS `cfg`.`MannerOfCollision` (
  `MannerOfCollisionID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MannerOfCollisionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfg`.`MotorisReadiness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`MotorisReadiness` ;

CREATE TABLE IF NOT EXISTS `cfg`.`MotorisReadiness` (
  `MotoristRedinessID` INT NOT NULL AUTO_INCREMENT,
  `State` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MotoristRedinessID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfg`.`PerastrianPosition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`PerastrianPosition` ;

CREATE TABLE IF NOT EXISTS `cfg`.`PerastrianPosition` (
  `PerastrianPositionID` INT NOT NULL AUTO_INCREMENT,
  `State` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PerastrianPositionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfg`.`RestraintType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`RestraintType` ;

CREATE TABLE IF NOT EXISTS `cfg`.`RestraintType` (
  `RestraintTypeID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RestraintTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfg`.`RoadCondition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`RoadCondition` ;

CREATE TABLE IF NOT EXISTS `cfg`.`RoadCondition` (
  `RoadConditionID` INT NOT NULL AUTO_INCREMENT,
  `Condition` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RoadConditionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfg`.`VehicleDamageClass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`VehicleDamageClass` ;

CREATE TABLE IF NOT EXISTS `cfg`.`VehicleDamageClass` (
  `VehicleDamageClassID` INT NOT NULL AUTO_INCREMENT,
  `VehicleDamageClass` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`VehicleDamageClassID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfg`.`VehicleType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`VehicleType` ;

CREATE TABLE IF NOT EXISTS `cfg`.`VehicleType` (
  `VehicleTypeID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`VehicleTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cfg`.`WeatherType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cfg`.`WeatherType` ;

CREATE TABLE IF NOT EXISTS `cfg`.`WeatherType` (
  `WeatherTypeID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `DateUpdated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`WeatherTypeID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
